### PR TITLE
Fix Linux Build system for 0.4.3

### PR DESCRIPTION
**Pull request by feilen**
So, I haven't got it completely _working_ on linux quite yet. There's still some issue where at least one thread doesn't properly get the GL info when starting up, and that causes it to hit a std::logic error when it tries to initialize a string off of a NULL const char *. But the UI starts and compiles fine, and it doesn't crash until you attempt to launch a game. I think it may be more productive to push this (finished) part up now and start an issue to fix the Linux launch.

### CODE REVIEW

**Comment by cegli** [comment]
Nice, looks good!  I've now merged it with my branch.  I'm not exactly sure what's going on with the NULL string.  It looks like line 382 of OGL/Render.cpp is failing to get a string.  Try putting a breakpoint at line 382

g_ogl_config.gl_vendor = (const char*)glGetString(GL_VENDOR);

and check what's going on.  You can compare the differences between the master (working) version, and this one and see if you can find where they differ.  Does launching it with the rift off help?  Maybe the Rift somehow interferes with that call?

**Comment by feilen** [comment]
That's where it's having an issue, for sure. But I can't work out why. I've
hit it with GDB and tried comparing with the master version, and could find
no obvious difference that would cause that to happen. One thing that could
be affecting it for sure is that I don't actually have a Rift yet, mine's
still in the mail. So I'm asking around for anyone running the Rift and
Linux, to see if someone can help me sort it out. The issue happens whether
you have 'VR Mode' on or not in the settings, so I still have some tracing
to do.

**Comment by feilen** [comment]
According to digging around on Google, apparently it only ever returns NULL
if there hasn't been a valid OpenGL context created. I believe that the
call used for DolphinWX to do this is wglCreateContext(). There are two
instances of this call in Dolphin/Core, and they're both in
Core/DolphinWX/GLInterface/WGL.cpp.

I added breakpoints to each, and neither ends up getting called before the
crash (aka, where it tries and fails to use glGetString, and gets a null
instead).

I can only assume that for some reason wglCreateContext isn't actually
getting called before the gl functions, so it doesn't have a proper GL
context.

I'm going to try the (theoretically working) upstream version to see if it
calls them beforehand, and if it does, then we've got the root of the
problem.

**Comment by feilen** [comment]
FOUND IT!

I guess on Linux, it binds to GLX as the GLInterface, while on Windows it
uses something else. It doesn't appear to have an MakeCurrentOffscreen, or
at least that call doesn't get the context. Anyway, so a GLX context gets
created, but then all the glGetString() and really any GL calls are called
at it, it fails to do anything.

So the reason it happily goes through without a openGL context? For
cInterfaceBase, MakeCurrentOffscreen doesn't get overridden, and instead
simply returns "true" by the base class, so it thinks it's valid. I'll try
whipping up a GLX definition, and see if I can't fill out the definition
for the other GL backends available.

**Pull request merged**
