### PR TITLE
Fix freelook sensitivity, pitch, lean back, etc. Start avatar drawing. Move Rift-specific stuff.

### PR DESCRIPTION
**Pull request by CarlKenner**
I finally fixed the freelook sensitivity, and changed it back to being global. And I fixed the issues with pitch and lean back angle. Now everything works like it is supposed to.

I also moved things around to be more readable, and I moved the Oculus SDK stuff out of some of the files and into vr.cpp. I want to make it easy to support other HMDs, and I want to isolate the non-GPL code as much as possible to make it more likely to be merged into master one day, perhaps with the version in master only supporting some other HMD while our branch adds Oculus Rift support.

And I started the code for drawing your controller in the VR world with you.

And I merged the latest code from master.

### CODE REVIEW

**Comment by cegli** [comment]
Hey Carl,

So far everything looks good, except for the regression in Free Look sensitivity.  The system of a single fixed value for free look is not a complete solution, because it only works properly when the scale is set to life-size.  When you start making the world bigger or smaller, the apparent free look size changes.

If you take a game, and make the scale very large, free look seems like it stops working all together, due to the step size being so small.  If you make the scale very small, the step size is way too large.  That was the whole reason I implemented that code.  It keeps the free-look step size the same in game, regardless of the scale.  Unfortunately, the way I fixed the scaling problem added a bug of messing up coherency between games, which I agree is very bad.  I addressed this with the per-game setting.

I do think there is probably a better way to automatically calculate a good per game value, and do away with that setting.  If you can think of a smooth way to do that, I am very interested.  That would be the best way to do it, and would address all of the issues.  Until then, I think we should put the scaling code and per game setting back in.

I like what you did with the angle correction code, looks like a smoother way of doing things.  Great work there.

Regarding dual core determinism mode in direct mode, it's required for it not to stutter.  Direct mode is useless right now without it.  I know that dual core determinism causes crashing with the Opcode Replay Buffer, but it would be better to force disabling of the Opcode Replay Buffer for now in direct mode.  I have a Opcode Replay Buffer disable fix like that in my local directory.  I will merge it once I've tested to make sure it doesn't break anything.  Eventually, I'll fix the Opcode Replay Buffer in dual core determinism mode.  I know why it's crashing in it, but haven't had the time to fix it yet.

**Comment by CarlKenner** [comment]
"So far everything looks good, except for the regression in Free Look sensitivity. The system of a single fixed value for free look is not a complete solution, because it only works properly when the scale is set to life-size. When you start making the world bigger or smaller, the apparent free look size changes."

Don't be an idiot.

"That was the whole reason I implemented that code."

No, the whole reason you implemented that code is because you didn't realise it was in metres, and you refused to listen when I told you it was in metres, and you set it to a value in Game Units which broke any game that didn't have exactly the right units per metre.

I fixed it, and it is scaled like you wanted. So please don't break it again. If you want to do something with freelook, you could make it analog when using an analog stick rather than digital.

"Regarding dual core determinism mode in direct mode, it's required for it not to stutter. Direct mode is useless right now without it. I know that dual core determinism causes crashing with the Opcode Replay Buffer, but it would be better to force disabling of the Opcode Replay Buffer for now in direct mode."

We can't have features enforced that cause a crash though. We should give people a choice if there are two things they can't use together.

**Comment by cegli** [comment]
I'm glad you at least edited your original message.  Come on Carl, be nice.  If someone doesn't agree with you, it doesn't automatically make them an idiot.  You should be able to hold a simple discussion with a developer without resorting to insults.

I didn't refuse to listen when you told me it was in metres.  I read each comment and even went back to look at the previous code.  I personally did not like the behavior at all.  I played around 16 hours of games with it before starting development, and was very annoyed by it.  Before changing the behavior back again, I once again checked out your latest branch and went into a couple games to give it a second chance.  I tried setting the scale very large and the free look camera was barely moving again.

"We can't have features enforced that cause a crash though. We should give people a choice if there are two things they can't use together.

That is why my latest commit makes sure that this crash can't happen.  It disables opcode replay in dual core determinism mode, which makes sense because it doesn't work in that mode right now anyway.  This stops that crash in both extended and direct mode.  

My thoughts were: 
1. The direct mode hack can be removed when direct mode works in any other mode.
2.  The opcode replay buffer disable hack can be removed once it works at all in dual core mode.  

Do you agree?

**Comment by CarlKenner** [comment]
Technically I said you were being an idiot, which isn't the same as saying you are an idiot.

You did accidentally break the freelook speed code by making an assumption without checking how a value was being used (which is easily done), which got stuck that way for months and annoyed a lot of users, and I did clear up your misconception that had led you to breaking it, and then rather than fixing it, you deliberately left your bug there and created a really awkward workaround that would have been a nightmare for users and developers. And then after I fixed your bug and got it working exactly how you wanted it, and removed your now unnecessary work-around, you had the nerve to call it a regression. Then when I pointed out you were being an idiot, you reverted (or at least attempted to, you missed a spot) my fix and went back to your totally broken code and really bad workaround.

So it is fair to say you were being an idiot rather than merely disagreeing with me when I was right. And you still are. I know you aren't actually an idiot, so take a step back, try the code which I fixed perfectly how you wanted, have a look at how it works, and go back to being smart again.

"That is why my latest commit makes sure that this crash can't happen. It disables opcode replay in dual core determinism mode, which makes sense because it doesn't work in that mode right now anyway. This stops that crash in both extended and direct mode."

That's good, thank you.

We can't be sure that direct mode is behaving the same way on all graphics cards and PCs, so we can't be sure it is juddering for everyone. And your opcode replay is really good and makes games so much better, so I'd prefer people to have a choice between opcode replay or (possibly) less stutter.

**Comment by cegli** [comment]
Haha, you always know the perfect thing to say to make me feel warm and fuzzy inside :-P.  To be fair, I didn't revert the code after you said I was being an idiot, I did it before, so it wasn't to spite you.  I personally thought my system was better than the _original_ system, though you're probably right that your latest code is much better (and more streamlined) than my code!  I probably should have checked your new code better before jumping to conclusions, and I didn't mean to insult you by calling it regression.  I don't think it's fair to act like I was deliberately trying to cause problems though.  I've always just wanted to make the code and experience better.  I will check it out again and give it a fair shake.

About direct mode, yeah, I thought about that...  I wish I had a Nvidia card too to be able to test a couple more configurations.  It's tricky to choose how much freedom to give to the user or how much to restrict them.  It would probably be better to warn them if they're in direct mode and don't have dual-core determinism enabled with a pop-up box warning that it may judder.  That way they can still try it if they want, but they'll know that it'll probably work better in dual-core determinism mode.  It will be easier for them to change now too, because that option is now a global setting in the graphics config.

**Comment by cegli** [comment]
Ahhhh, I've found where the communication break-down was.  You've got it nicely fixed so that if you adjust the global scale, it always keeps the free-look consistent (perfect).  I tried changing the scale through the VR Hotkeys, which still makes the free-look size change!  When I originally tested it, I thought you had reverted it completely to the way it worked before, but this is a much better system.  

I think the best thing to do is to add another option to the VR Hotkeys so we can control global scale with KBM/XInput/DInput.  That way, people can tune the scale in-game, without altering free-look step size, without having to go through the menus.  I will revert my revert as well.

Also, do you think having a per-game option for free-look step size is a bad idea?  It's kind of hidden away right now.  It would default to 1, but then users could change tune it for each game if they wanted.  I thought it would be nice, but maybe you disagree.

**Pull request merged**
